export const  login = '/auth/login',
createVenue='/venue/create',
cities='/common/cities',
categories='/common/categories?type=VENUE',
getSubCategories='/venue/menu/subcategories',
articlesCategories='/common/categories?type=ARTICLE',
attractionCategories='/common/categories?type=ATTRACTION',
menuCategories='/common/categories?type=MENU',
eventCategories='/common/categories?type=EVENT',
countries='/common/countries',
currency='/common/currency',
interests='/common/interests',
location='/location/list/all',
getTimeSlots ='/venue/timeslot/venueid',
getDays='/venue/getdays',
addTimeSlots = '/venue/timeslot',
updateTimeSlots = '/venue/update/timeslot',
addZone='/venue/zone',
updateZone='/venue/update/zone',
addEventZone='/event/zone',
updateEventZone='/event/update/zone',
addAttractionZone='/attraction/zone',
getZoneSlots ='/venue/zone/venueid',
getEventZone ='/event/zones/list',
getAttractionZone ='/attraction/zones/list',
addPriceType='/venue/pricetype',
updatePriceType='/venue/update/pricetype',
addVoucher ='/venue/voucher',
updateVoucher ='/venue/update/voucher',
getVouchers='/venue/voucher/venueid',
getPackages='/venue/package/venue',
getMenu='/venue/menu/venueid',
getMedia='/venue/media/venueid',
addSection='/venue/section',
addGroup='/venue/group',
getSection='/venue/section',
getGroup='/venue/group',
getPolicy='/venue/policy',
getPriceType ='/venue/pricetype/venueid',
getUsers='/user/list',
groupMembers='/venue/group/member',
addPackage='/venue/package',
updatePackage='/venue/update/package',
getMediaType='/venue/mediatype',
addMedia = '/venue/media',
addMenu='/venue/menu',
uploadImages = '/common/upload/images',
getTags = '/article/tags?pageNumber=1&perPage=10',
getUsedTags = '/article/tags/used?pageNumber=1&perPage=10',
addArticles = '/article/create',
updateArticles = '/article/update',
getArticles ='/article/getarticlesbyuser',
getEvents ='/event/getevents',
getEvent ='/event',
getArticlesCategories='/article/categories/used?pageNumber=1&perPage=10',
getMenuIcons = 'venue/menu/listicons',
eventIcons = 'event/infoiconslist',
getEventShowInfo ='event/showinfo',
getAttractionShowInfo ='attraction/show',
addEvent='event/create',
getVenues='/venue/getvenues',
addShowInfo='/event/showinfo/create',
updateShowInfo='/event/showinfo/update',
addAttractionShowInfo='/attraction/show/create',
updateAttractionShowInfo='/attraction/show/update',
getSetting='/event/showinfo/settings',
getArtist='/common/artists',
addEventPriceType='/event/pricetype/create',
updateEventPriceType='/event/update/pricetype',
addAttractionPriceType='/attraction/pricetype/create',
getAttractionPriceType='/attraction/pricetype/attractionId',
getEventPriceType='/event/pricetype/eventId',
getEventSettings='/event/showinfo/settings',
setEventSettings = '/event/showinfo/settings',
addPlugin='/event/plugin/create',
addAttractionPlugin='/attraction/plugin/create',
getPlugins='/event/plugin/eventId',
getAttractionPlugins='/attraction/plugin/attractionId',
attractionIcons = '/attraction/infoiconslist',
addAttraction='/attraction/create',

offersList='/offer/voucher/list',
offersPackagesList='/offer/package',
offersSeasonPackagesList='/offer/seasonpackages',
offersShowInfo='/offer/showinfo',
addOfferVoucher='/offer/voucher',
offerEventList='/offer/event/list',
offerVenueList='/offer/venue/list',
offerAttractionList='/offer/attraction/list',
getOfferSection='/offer/section',
getOfferGroup='/offer/group',
addOfferGroup='/offer/group',
addOfferSection='/offer/section',
addOfferPackage='/offer/package',
register='/auth/register',
feeds='/feeds/posts/list',
feedsModeration='/feeds/moderations',
getLocations='/location/lists/all'
